WHAT = countBit1

fast: $(WHAT).cpp
	g++ $(WHAT).cpp

$(WHAT): $(WHAT).cpp
	g++  $(WHAT).cpp


#	dvips -t letter $(WHAT).dvi
#	ps2pdf $(WHAT).ps

#clean:
#	rm *.log *.aux *.bbl *.blg *.ent $(WHAT).dvi $(WHAT).ps $(WHAT).pdf

